language: php

php:
- 7.1
- 7.2
- 7.3


before_install:
- echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
- travis_wait composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
- composer validate --no-check-lock --strict
- vendor/bin/phpunit --bootstrap vendor/autoload.php Tests/